DEBUG 2021-06-11 09:18:59.396 UTC: 	 CRAB Client version: v3.210601
DEBUG 2021-06-11 09:18:59.397 UTC: 	 Running on: Linux lxplus711.cern.ch 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-11 09:18:59.397 UTC: 	 Executing command: 'submit'
DEBUG 2021-06-11 09:18:59.398 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
INFO 2021-06-11 09:18:59.399 UTC: 	 Will use CRAB configuration file crabcode_2018/MuonEG_Run2018A_cfg.py
DEBUG 2021-06-11 09:18:59.399 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-06-11 09:18:59.415 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-06-11 09:18:59.434 UTC: 	 Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab2018/crab_MuonEG_Run2018A' already exists 
Please change the requestName in the config file
ERROR 2021-06-11 09:18:59.435 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/ClientUtilities.py", line 399, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab2018/crab_MuonEG_Run2018A' already exists 
Please change the requestName in the config file
INFO 2021-06-11 09:18:59.439 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab.log
DEBUG 2021-06-11 09:18:59.833 UTC: 	 CRAB Client version: v3.210601
DEBUG 2021-06-11 09:18:59.833 UTC: 	 Running on: Linux lxplus711.cern.ch 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-11 09:18:59.833 UTC: 	 Executing command: 'submit'
DEBUG 2021-06-11 09:18:59.834 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
INFO 2021-06-11 09:18:59.835 UTC: 	 Will use CRAB configuration file crabcode_2018/MuonEG_Run2018B_cfg.py
DEBUG 2021-06-11 09:18:59.835 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-06-11 09:18:59.864 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-06-11 09:18:59.865 UTC: 	 Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab2018/crab_MuonEG_Run2018B' already exists 
Please change the requestName in the config file
ERROR 2021-06-11 09:18:59.865 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/ClientUtilities.py", line 399, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab2018/crab_MuonEG_Run2018B' already exists 
Please change the requestName in the config file
INFO 2021-06-11 09:18:59.868 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab.log
DEBUG 2021-06-11 09:19:00.275 UTC: 	 CRAB Client version: v3.210601
DEBUG 2021-06-11 09:19:00.276 UTC: 	 Running on: Linux lxplus711.cern.ch 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-11 09:19:00.276 UTC: 	 Executing command: 'submit'
DEBUG 2021-06-11 09:19:00.276 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
INFO 2021-06-11 09:19:00.277 UTC: 	 Will use CRAB configuration file crabcode_2018/MuonEG_Run2018C_cfg.py
DEBUG 2021-06-11 09:19:00.278 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-06-11 09:19:00.297 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-06-11 09:19:00.344 UTC: 	 Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab2018/crab_MuonEG_Run2018C' already exists 
Please change the requestName in the config file
ERROR 2021-06-11 09:19:00.345 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/ClientUtilities.py", line 399, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab2018/crab_MuonEG_Run2018C' already exists 
Please change the requestName in the config file
INFO 2021-06-11 09:19:00.348 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab.log
DEBUG 2021-06-11 09:19:00.743 UTC: 	 CRAB Client version: v3.210601
DEBUG 2021-06-11 09:19:00.743 UTC: 	 Running on: Linux lxplus711.cern.ch 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-11 09:19:00.743 UTC: 	 Executing command: 'submit'
DEBUG 2021-06-11 09:19:00.744 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
INFO 2021-06-11 09:19:00.745 UTC: 	 Will use CRAB configuration file crabcode_2018/MuonEG_Run2018D_cfg.py
DEBUG 2021-06-11 09:19:00.745 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-06-11 09:19:00.800 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-06-11 09:19:00.801 UTC: 	 Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab2018/crab_MuonEG_Run2018D' already exists 
Please change the requestName in the config file
ERROR 2021-06-11 09:19:00.801 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/ClientUtilities.py", line 399, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab2018/crab_MuonEG_Run2018D' already exists 
Please change the requestName in the config file
INFO 2021-06-11 09:19:00.805 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab.log
DEBUG 2021-06-18 06:31:43.136 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-06-18 06:31:43.136 UTC: 	 Running on: Linux lxplus751.cern.ch 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-18 06:31:43.136 UTC: 	 Executing command: 'submit'
DEBUG 2021-06-18 06:31:43.137 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
INFO 2021-06-18 06:31:43.137 UTC: 	 Will use CRAB configuration file crabcode_2018/MuonEG_Run2018A_cfg.py
DEBUG 2021-06-18 06:31:43.138 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-06-18 06:31:43.141 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-06-18 06:31:43.141 UTC: 	 Cannot find the file ./WWG_crab_script_fakable specified in the JobType.scriptExe configuration parameter.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2021-06-18 06:31:43.141 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 95, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Cannot find the file ./WWG_crab_script_fakable specified in the JobType.scriptExe configuration parameter.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2021-06-18 06:31:43.144 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab.log
DEBUG 2021-06-22 16:10:04.479 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-06-22 16:10:04.480 UTC: 	 Running on: Linux lxplus733.cern.ch 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-22 16:10:04.480 UTC: 	 Executing command: 'status'
DEBUG 2021-06-22 16:10:04.480 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
DEBUG 2021-07-06 09:44:41.966 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-07-06 09:44:41.967 UTC: 	 Running on: Linux lxplus714.cern.ch 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-07-06 09:44:41.967 UTC: 	 Executing command: 'status'
DEBUG 2021-07-06 09:44:41.967 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-07-06 09:44:41.968 UTC: 	 Error: crab2018/crab_EGamma_Run2018D is not a valid CRAB project directory.
ERROR 2021-07-06 09:44:41.968 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2018/crab_EGamma_Run2018D is not a valid CRAB project directory.
INFO 2021-07-06 09:44:41.994 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakerate_crab/crab.log
DEBUG 2021-07-07 07:29:57.896 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-07-07 07:29:57.897 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-07-07 07:29:57.897 UTC: 	 Executing command: 'resubmit'
DEBUG 2021-07-07 07:29:57.898 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-07-07 07:29:57.902 UTC: 	 Error: crab2018/crab_EGamma_Run2018D is not a valid CRAB project directory.
ERROR 2021-07-07 07:29:57.902 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/resubmit.py", line 26, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2018/crab_EGamma_Run2018D is not a valid CRAB project directory.
INFO 2021-07-07 07:29:57.960 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakerate_crab/crab.log
DEBUG 2021-07-07 08:15:17.725 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-07-07 08:15:17.726 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-07-07 08:15:17.726 UTC: 	 Executing command: 'status'
DEBUG 2021-07-07 08:15:17.727 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-07-07 08:15:17.729 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakerate_crab/crab2018/crab_TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8_2018
ERROR 2021-07-07 08:15:17.729 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 650, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 512, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakerate_crab/crab2018/crab_TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8_2018
INFO 2021-07-07 08:15:17.739 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakerate_crab/crab.log
DEBUG 2021-11-18 06:56:22.162 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-11-18 06:56:22.163 UTC: 	 Running on: Linux lxplus791.cern.ch 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-11-18 06:56:22.163 UTC: 	 Executing command: 'submit'
DEBUG 2021-11-18 06:56:22.163 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
INFO 2021-11-18 06:56:22.164 UTC: 	 Will use CRAB configuration file crabcode_2016/DoubleEG_Run2016G_cfg.py
DEBUG 2021-11-18 06:56:22.164 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-11-18 06:56:22.218 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-11-18 06:56:22.218 UTC: 	 Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2016post/fakelepton_crab/crab2016/crab_DoubleEG_Run2016G' already exists 
Please change the requestName in the config file
ERROR 2021-11-18 06:56:22.219 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.01/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.01/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.01/lib/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2016post/fakelepton_crab/crab2016/crab_DoubleEG_Run2016G' already exists 
Please change the requestName in the config file
INFO 2021-11-18 06:56:22.234 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2016post/fakelepton_crab/crab.log
DEBUG 2022-01-28 10:12:33.383 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 10:12:33.384 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 10:12:33.384 UTC: 	 Executing command: 'status'
DEBUG 2022-01-28 10:12:33.384 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 10:12:33.850 UTC: 	 Error: crab2016/crab_TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8_2016 is not a valid CRAB project directory.
ERROR 2022-01-28 10:12:33.850 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 47, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2016/crab_TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8_2016 is not a valid CRAB project directory.
INFO 2022-01-28 10:12:35.739 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2016post/fakelepton_crab/crab.log
DEBUG 2022-01-28 17:39:59.285 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 17:39:59.285 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 17:39:59.285 UTC: 	 Executing command: 'remake'
DEBUG 2022-01-28 17:39:59.294 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
DEBUG 2022-01-28 17:39:59.371 UTC: 	 Checking credentials
DEBUG 2022-01-28 17:39:59.371 UTC: 	 Found proxy file /tmp/x509up_u110046
DEBUG 2022-01-28 17:39:59.371 UTC: 	 Getting proxy life time left
DEBUG 2022-01-28 17:39:59.371 UTC: 	 Executing command :
 voms-proxy-info --actimeleft --timeleft --file /tmp/x509up_u110046
DEBUG 2022-01-28 17:40:00.861 UTC: 	 output : 568026
568026

 error: 
 retcode : 0
DEBUG 2022-01-28 17:40:00.861 UTC: 	 Proxy valid for 157:47:06 hours
DEBUG 2022-01-28 17:40:01.192 UTC: 	 Encoded data for curl request: subresource=delegatedn
DEBUG 2022-01-28 17:40:01.193 UTC: 	 Executing command :
 curl -v -X GET -H "User-Agent: CRABClient/v3.211130" -H "Accept: */*" --data @/tmp/curlData5_PNrV --cert "/tmp/x509up_u110046" --key "/tmp/x509up_u110046" --capath "/etc/grid-security/certificates/" "https://cmsweb.cern.ch:8443/crabserver/prod/info?subresource=delegatedn" | tee /dev/stderr 
DEBUG 2022-01-28 17:40:01.342 UTC: 	 output : {"result": [
 {"services": ["/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch|/DC=ch/DC=cern/OU=computers/CN=dciangot-tw.cern.ch"]}
]}

 error:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 137.138.120.6...
* TCP_NODELAY set
* Connected to cmsweb.cern.ch (137.138.120.6) port 8443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: /etc/grid-security/certificates/
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [109 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [6224 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
{ [13495 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
} [6615 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
} [264 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: DC=ch; DC=cern; OU=computers; CN=cmsweb.cern.ch
*  start date: Feb  2 08:08:53 2021 GMT
*  expire date: Mar  9 08:08:53 2022 GMT
*  subjectAltName: host "cmsweb.cern.ch" matched cert's "cmsweb.cern.ch"
*  issuer: DC=ch; DC=cern; CN=CERN Grid Certification Authority
*  SSL certificate verify ok.
} [5 bytes data]
> GET /crabserver/prod/info?subresource=delegatedn HTTP/1.1
> Host: cmsweb.cern.ch:8443
> User-Agent: CRABClient/v3.211130
> Accept: */*
> Content-Length: 22
> Content-Type: application/x-www-form-urlencoded
> 
} [22 bytes data]
* upload completely sent off: 22 out of 22 bytes
{ [5 bytes data]
< HTTP/1.1 200 OK
< Date: Fri, 28 Jan 2022 17:40:01 GMT
< Server: nginx/1.17.10
< Content-Type: application/json
< Content-Length: 213
< Vary: Accept
< Cache-Control: max-age=3600
< X-Rest-Status: 100
< Etag: "de92dcb56f87dabbe30965e60a433c3f1b873eab"
< X-Rest-Time: 2215.862 us
< CMS-Server-Time: D=15683 t=1643391601319971
< 
{ [5 bytes data]
100   235  100   213  100    22   3550    366 --:--:-- --:--:-- --:--:--  3983
* Connection #0 to host cmsweb.cern.ch left intact
{"result": [
 {"services": ["/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch|/DC=ch/DC=cern/OU=computers/CN=dciangot-tw.cern.ch"]}
]}

 retcode : 0
DEBUG 2022-01-28 17:40:01.343 UTC: 	 Registering user credentials on myproxy for /DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch|/DC=ch/DC=cern/OU=computers/CN=dciangot-tw.cern.ch
DEBUG 2022-01-28 17:40:01.343 UTC: 	 Executing command :
 voms-proxy-info --identity --file /tmp/x509up_u110046
DEBUG 2022-01-28 17:40:02.914 UTC: 	 output : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=yian/CN=826694/CN=Ying An

 error: 
 retcode : 0
DEBUG 2022-01-28 17:40:02.915 UTC: 	 Getting myproxy life time left for b52ac606a6f7097e9b4b8f05a3a67cc69f8f291b
DEBUG 2022-01-28 17:40:02.915 UTC: 	 Executing command :
 myproxy-info -s myproxy.cern.ch -l b52ac606a6f7097e9b4b8f05a3a67cc69f8f291b
DEBUG 2022-01-28 17:40:03.704 UTC: 	 output : username: b52ac606a6f7097e9b4b8f05a3a67cc69f8f291b
owner: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=yian/CN=826694/CN=Ying An
  renewal policy: /DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch|/DC=ch/DC=cern/OU=computers/CN=dciangot-tw.cern.ch
  trusted retrieval policy: /DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch|/DC=ch/DC=cern/OU=computers/CN=dciangot-tw.cern.ch
  timeleft: 496:52:24  (20.7 days)

 error: 
 retcode : 0
DEBUG 2022-01-28 17:40:03.705 UTC: 	 Myproxy is valid: 1788720
DEBUG 2022-01-28 17:40:03.705 UTC: 	 Result of myproxy credential check:
  Credential exists on myproxy: username: b52ac606a6f7097e9b4b8f05a3a67cc69f8f291b  - validity: 20 days, 16:52:00
DEBUG 2022-01-28 17:40:03.705 UTC: 	 Command use: remake
DEBUG 2022-01-28 17:40:03.705 UTC: 	 Options use: ['--task=220128_075148:yian_crab_TTGJets_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8_2016']
DEBUG 2022-01-28 17:40:03.706 UTC: 	 Encoded data for curl request: subresource=version
DEBUG 2022-01-28 17:40:03.706 UTC: 	 Executing command :
 curl -v -X GET -H "User-Agent: CRABClient/v3.211130" -H "Accept: */*" --data @/tmp/curlDataRb0piD --cert "/tmp/x509up_u110046" --key "/tmp/x509up_u110046" --capath "/etc/grid-security/certificates/" "https://cmsweb.cern.ch:8443/crabserver/prod/info?subresource=version" | tee /dev/stderr 
DEBUG 2022-01-28 17:40:04.208 UTC: 	 output : {"result": [
 ["3.3.19", "3.3.20", "v3", "development", "py3.220124"]
]}

 error:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 137.138.120.6...
* TCP_NODELAY set
* Connected to cmsweb.cern.ch (137.138.120.6) port 8443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: /etc/grid-security/certificates/
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [109 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [6224 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
{ [13495 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
} [6615 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
} [264 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: DC=ch; DC=cern; OU=computers; CN=cmsweb.cern.ch
*  start date: Feb  2 08:08:53 2021 GMT
*  expire date: Mar  9 08:08:53 2022 GMT
*  subjectAltName: host "cmsweb.cern.ch" matched cert's "cmsweb.cern.ch"
*  issuer: DC=ch; DC=cern; CN=CERN Grid Certification Authority
*  SSL certificate verify ok.
} [5 bytes data]
> GET /crabserver/prod/info?subresource=version HTTP/1.1
> Host: cmsweb.cern.ch:8443
> User-Agent: CRABClient/v3.211130
> Accept: */*
> Content-Length: 19
> Content-Type: application/x-www-form-urlencoded
> 
} [19 bytes data]
* upload completely sent off: 19 out of 19 bytes
{ [5 bytes data]
< HTTP/1.1 200 OK
< Date: Fri, 28 Jan 2022 17:40:04 GMT
< Server: nginx/1.17.10
< Content-Type: application/json
< Content-Length: 73
< Vary: Accept
< Cache-Control: max-age=3600
< X-Rest-Status: 100
< Etag: "3309a93c90cdb00bd297a532c9c67f645a0b4b24"
< X-Rest-Time: 233719.587 us
< CMS-Server-Time: D=265777 t=1643391603912596
< 
{ [5 bytes data]
100    92  100    73  100    19    197     51 --:--:-- --:--:-- --:--:--   248
* Connection #0 to host cmsweb.cern.ch left intact
{"result": [
 ["3.3.19", "3.3.20", "v3", "development", "py3.220124"]
]}

 retcode : 0
DEBUG 2022-01-28 17:40:04.209 UTC: 	 CRABClient version: v3.211130
DEBUG 2022-01-28 17:40:04.209 UTC: 	 Instance is prod
DEBUG 2022-01-28 17:40:04.209 UTC: 	 Server base url is cmsweb.cern.ch
DEBUG 2022-01-28 17:40:04.209 UTC: 	 Command api workflow
INFO 2022-01-28 17:40:04.209 UTC: 	 Remaking crab_TTGJets_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8_2016 folder.
INFO 2022-01-28 17:40:04.347 UTC: 	 Remaking .requestcache file.
INFO 2022-01-28 17:40:04.505 UTC: 	 Success: Finished remaking project directory crab_TTGJets_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8_2016
INFO 2022-01-28 17:40:04.579 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2016post/fakelepton_crab/crab.log
